### ISSUE TITLE
Move descriptions should not display "This move can’t be used. It’s recommended that this move is forgotten. Once forgotten, this move can’t be remembered."

### ISSUE THREAD

**Issue by ChronicDelusionist** [kinostl/pokeymanz-generator#4]
The tool overall works great for its intended purpose! The only real issue I've found for regular use is that sometimes, with Pokemon like Bidoof, it seems to pull from a game where its Moves could be carried in from another gen and don't work in the game. This results in a long list of non-descriptions for a moveset, which could be a problem for GMs looking up a Pokemon on the fly.

Recommendation: Unified Move database (this would be hard...) or the ability to pick the game the moves are pulled from defaulting to the latest gen?

**Comment by kinostl** [comment]
Was just about to file this. Easy fix, just need to filter out anything with the description of `This move can’t be used. It’s recommended that this move is forgotten. Once forgotten, this move can’t be remembered.`. 

Adding Ability to Pick the Game as a Feature Request.

**Comment by kinostl** [comment]
Completed by #19
